dist: xenial
language: python
sudo: false

python:
  - '3.6'
  - '3.7'
  - '3.8'

addons:
  postgresql: '9.6'

env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=2.2,<3.0"
    - DJANGO=">=3.0,<3.1"
    - DJANGO=">=3.1,<3.2"
install:
  - pip install -q coverage flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE django_timezone_field;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=98
